"""add_telemetry_semantics

Revision ID: 8a9b0c1d2e3f
Revises: ed9d06672eca
Create Date: 2026-09-08 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a9b0c1d2e3f'
down_revision: Union[str, Sequence[str], None] = 'ed9d06672eca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telemetry', sa.Column('http_status_code', sa.Integer(), nullable=True))
    op.add_column('telemetry', sa.Column('span_kind', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telemetry', 'span_kind')
    op.drop_column('telemetry', 'http_status_code')
    # ### end Alembic commands ###
