"""add detection models

Revision ID: bc1eee7578f3
Revises: 8a9b0c1d2e3f
Create Date: 2026-09-08 12:04:40.386749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc1eee7578f3'
down_revision: Union[str, Sequence[str], None] = '8a9b0c1d2e3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detector_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('detector_type', sa.String(length=50), nullable=False),
    sa.Column('feature', sa.String(length=100), nullable=False),
    sa.Column('aggregation_function', sa.String(length=50), nullable=False),
    sa.Column('min_raw_samples', sa.Integer(), nullable=False),
    sa.Column('min_baseline_observations', sa.Integer(), nullable=False),
    sa.Column('cooldown_windows', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_id', 'detector_type', 'feature', 'version', name='uq_detector_logical_version')
    )
    op.create_index(op.f('ix_detector_configs_id'), 'detector_configs', ['id'], unique=False)
    op.create_index('ix_detector_configs_logical', 'detector_configs', ['service_id', 'detector_type', 'feature'], unique=False)
    op.create_index(op.f('ix_detector_configs_service_id'), 'detector_configs', ['service_id'], unique=False)
    op.create_table('anomaly_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('detector_config_id', sa.Uuid(), nullable=False),
    sa.Column('config_version', sa.Integer(), nullable=False),
    sa.Column('detector_type', sa.String(length=50), nullable=False),
    sa.Column('feature', sa.String(length=100), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('cooldown_count', sa.Integer(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['detector_config_id'], ['detector_configs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_id', 'detector_config_id', 'config_version', 'feature', 'window_start', name='uq_anomaly_identity')
    )
    op.create_index(op.f('ix_anomaly_events_detector_config_id'), 'anomaly_events', ['detector_config_id'], unique=False)
    op.create_index(op.f('ix_anomaly_events_id'), 'anomaly_events', ['id'], unique=False)
    op.create_index(op.f('ix_anomaly_events_service_id'), 'anomaly_events', ['service_id'], unique=False)
    op.create_index(op.f('ix_anomaly_events_status'), 'anomaly_events', ['status'], unique=False)
    op.create_index(op.f('ix_anomaly_events_window_start'), 'anomaly_events', ['window_start'], unique=False)
    op.create_index('ix_anomaly_service_window', 'anomaly_events', ['service_id', 'window_start'], unique=False)
    # (Partition drops removed)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # (Partition creations removed)
    op.drop_index('ix_anomaly_service_window', table_name='anomaly_events')
    op.drop_index(op.f('ix_anomaly_events_window_start'), table_name='anomaly_events')
    op.drop_index(op.f('ix_anomaly_events_status'), table_name='anomaly_events')
    op.drop_index(op.f('ix_anomaly_events_service_id'), table_name='anomaly_events')
    op.drop_index(op.f('ix_anomaly_events_id'), table_name='anomaly_events')
    op.drop_index(op.f('ix_anomaly_events_detector_config_id'), table_name='anomaly_events')
    op.drop_table('anomaly_events')
    op.drop_index(op.f('ix_detector_configs_service_id'), table_name='detector_configs')
    op.drop_index('ix_detector_configs_logical', table_name='detector_configs')
    op.drop_index(op.f('ix_detector_configs_id'), table_name='detector_configs')
    op.drop_table('detector_configs')
    # ### end Alembic commands ###
