"""implement_telemetry_foundation

Revision ID: ed9d06672eca
Revises: f0c1c0dca9e4
Create Date: 2026-09-08 11:18:20.168278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed9d06672eca'
down_revision: Union[str, Sequence[str], None] = 'f0c1c0dca9e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('ingestion_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('telemetry_type', sa.String(length=20), nullable=False),
    sa.Column('trace_id', sa.String(length=32), nullable=True),
    sa.Column('span_id', sa.String(length=16), nullable=True),
    sa.Column('parent_span_id', sa.String(length=16), nullable=True),
    sa.Column('severity_number', sa.Integer(), nullable=True),
    sa.Column('metric_name', sa.String(length=255), nullable=True),
    sa.Column('metric_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('resource_attributes', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.String(), 'sqlite'), nullable=True),
    sa.Column('event_attributes', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.String(), 'sqlite'), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.String(), 'sqlite'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'timestamp'),
    sa.UniqueConstraint('fingerprint', 'timestamp', name='uq_telemetry_fingerprint_timestamp'),
    postgresql_partition_by='RANGE (timestamp)'
    )
    op.create_index(op.f('ix_telemetry_id'), 'telemetry', ['id'], unique=False)
    op.create_index(op.f('ix_telemetry_service_id'), 'telemetry', ['service_id'], unique=False)
    op.create_index(op.f('ix_telemetry_trace_id'), 'telemetry', ['trace_id'], unique=False)
    op.create_table('machine_credentials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=True),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('api_key_hash', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machine_credentials_id'), 'machine_credentials', ['id'], unique=False)
    op.create_index(op.f('ix_machine_credentials_is_active'), 'machine_credentials', ['is_active'], unique=False)
    op.create_index(op.f('ix_machine_credentials_key_prefix'), 'machine_credentials', ['key_prefix'], unique=True)
    op.create_index(op.f('ix_machine_credentials_service_id'), 'machine_credentials', ['service_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_machine_credentials_service_id'), table_name='machine_credentials')
    op.drop_index(op.f('ix_machine_credentials_key_prefix'), table_name='machine_credentials')
    op.drop_index(op.f('ix_machine_credentials_is_active'), table_name='machine_credentials')
    op.drop_index(op.f('ix_machine_credentials_id'), table_name='machine_credentials')
    op.drop_table('machine_credentials')
    op.drop_index(op.f('ix_telemetry_trace_id'), table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_service_id'), table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_id'), table_name='telemetry')
    op.drop_table('telemetry')
    # ### end Alembic commands ###
